- name:  set-timezone Asia/Taipei
  shell: timedatectl set-timezone Asia/Taipei
  ignore_errors: yes
  tags:  [common]

- name:  Extra Packages for Enterprise Linux (or EPEL) is present
  yum: 
     name: epel-release 
     state: latest  
  ignore_errors: yes
  tags: [common]

- name: clean 1
  shell: rm -f /var/lib/rpm/__db*
  ignore_errors: yes
  tags:  [common]

- name: clean 2
  shell: rpm  --rebuilddb
  ignore_errors: yes
  tags:  [common]


- name: clean 3
  shell: yum clean all
  ignore_errors: yes
  tags:  [common]

- name: clean 4
  shell: yum update
  ignore_errors: yes
  tags:  [common]



- name: CentOS files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ centos_files }}"
  tags: [common]

- name: epel-release install
  shell: yum install -y epel-release
  ignore_errors: yes
  tags:  [common]


- name: selenix  policycoreutils
  yum: 
    name: policycoreutils-python 
    state: present
  ignore_errors: yes
  tags: [common]

- name: selenix policies 1
  shell: semanage port -a -t mysqld_port_t -p tcp {{ item }}
  with_items:
    - 24901
    - 24902
    - 24903
    - 24904    
    - 3306
    - 33060
    - 33061
    - 3307
    - 33070
    - 6446
    - 64460
    - 6447
    - 64470
  ignore_errors: yes
  tags: [common]

- name: selenix policies 2
  shell: setsebool -P httpd_can_network_connect true
  ignore_errors: yes
  tags: [common]


- name: firewalld  policies
  shell:  firewall-cmd --zone=public --add-port={{ item }}/tcp --permanent
  with_items:
    - 24901
    - 24902
    - 24903
    - 24904    
    - 3306
    - 33060
    - 33061
    - 3307
    - 33070
    - 6446
    - 64460
    - 6447
    - 64470
  ignore_errors: yes
  tags: [common]


- name: CentOS Daemon is reloaded
  command: systemctl daemon-reload
  tags: [common]

#- name: Centos sshd service is restarted
#  service:
#    name: sshd
#    state: restarted
#  tags: [common]
  
- name: JQ is present
  yum: 
    name: jq 
    state: present  
  tags: [common]

- name: htop is present
  yum:
    name: htop
    state: present
  tags: [common]
  
- name: KILLALL is present
  yum: 
    name: psmisc 
    state: present
  ignore_errors: yes
  tags: [common]
  
- name: Host is present
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.host_ip }}"
    line: "{{ item.host_ip }} {{ item.host_name }}"
  with_items: "{{ hosts }}"
  tags: [common]
 

- name: Services are not running
  service:
    name: "{{ item }}"
    state: stopped
  ignore_errors: yes
  with_items: "{{  obsolete_services }}"
  tags: [common]
