# -*- mode: ruby -*-
# vi: set ft=ruby :
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
  else
    config.vm.synced_folder ".", "/vagrant"
  end
  config.vm.define "cd" do |d|
    d.vm.box = "bento/centos-7.5"
    d.vm.hostname = "cd"
    d.vm.network "private_network", ip: "10.100.198.200"
    d.vm.provision :shell, path: "scripts/bootstrap4CentOs_ansible.sh"
#    d.vm.provision :shell, inline: "PYTHONUNBUFFERED=1 ansible-playbook /vagrant/ansible/cd.yml -c local"
    d.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]            
      v.memory = 2048
    end
  end  
  (1..4).each do |i|
    config.vm.define "mysql-#{i}" do |d|
      d.vm.box = "bento/centos-7.5"
      d.vm.hostname = "mysql-#{i}"
      d.vm.network "private_network", ip: "10.100.197.20#{i}"
      d.vm.provider "virtualbox" do |v|
        v.memory = 1536
        v.cpus = 1
      end
    end
  end
   (1..2).each do |i|
    config.vm.define "mysqlrouter-#{i}" do |d|
      d.vm.box = "bento/centos-7.5"
      d.vm.hostname = "mysql-#{i}"
      d.vm.network "private_network", ip: "10.100.197.21#{i}"
      d.vm.provider "virtualbox" do |v|
        v.memory = 1536
        v.cpus = 1
      end
    end
  end
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
    config.vbguest.no_install = true
    config.vbguest.no_remote = true
  end
end
