version: '2'

services:
  mysqldb:
    container_name: mysql
    image: mysql/mysql-server:8.0.11-1.1.5
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /mnt/sdb/mysql_data:/var/lib/mysql
    - $PWD/my55.cnf:/etc/my.cnf
    environment:
    - MYSQL_ROOT_PASSWORD=qazwsx
    - MYSQL_DATABASE=ec
    - MYSQL_USER=ecuser
    - MYSQL_PASSWORD=qazwsx
    - EXTRA_OPTS="--lower_case_table_names=1"
    - TZ=Asia/Taipei
    network_mode:  "host"
